import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import Header from "./(components)/Header";
import "./globals.css";

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="bg-my-dark text-white">
        <div className="grid grid-cols-10 gap-5 mx-auto max-w-7xl px-40">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}

// ${notoSansJP.className}