version: "3"
services:
  db:
    image: mysql:8.0.35
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: frkawa_blog_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/app
      - gem_data:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - frkawa-blog_default
  next:
    build:
      dockerfile: ./next/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./next:/app
    ports:
      - "8000:3000"
    networks:
      - frkawa-blog_default
volumes:
  mysql_data:
  gem_data:
networks:
  frkawa-blog_default:
    external: true
