name: Run RSpec, Rubocop

on:
  push:

jobs:
  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rails
    services:
      mysql:
        image: mysql:8.0.35
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Database create and migrate
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run RSpec
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rails
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run rubocop
        run: bundle exec rubocop

  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn

      - name: Run eslint
        run: yarn lint
